#299: Endpoint to fetch transactions for a list of addresses
alephium/explorer-backend pull request #387
Opened 2022-11-16 03:06 UTC by simerplaha

- Resolves #299
- Following `areAddressesActive` this endpoint is also a `POST` request. 
  - Endpoint: `/addresses/transactions`
  - Requires array of addresses as JSON body `["address1", "address2"]`

2022-11-16 13:45 UTC, tdroxler commented
pinging @nop33 just to validate it's what you need

2022-11-16 14:26 UTC, tdroxler requested changes
Can you add a test in `ExplorerSpec` please? This file is a bit like our it:test, it makes sure every part of the code is well plugged when calling the endpoint.

Otherwise LGTM

2022-11-16 14:48 UTC, nop33 commented
What is the limit of number of addresses that I can provide in the JSON body?

2022-11-17 03:39 UTC, simerplaha commented
> What is the limit of number of addresses that I can provide in the JSON body?

Max limit is `80` addresses (`groupNum` * [`gapLimit`](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#address-gap-limit) i.e. `4 * 20`) similar to `/addresses-active`

Over `80` and the response is 

```json
{
    "detail": "Invalid value for: body (expected size of value to be less than or equal to 80, but was 81)"
}
```

> Can you add a test in ExplorerSpec please? This file is a bit like our it:test, it makes sure every part of the code is well plugged when calling the endpoint.

Added tests to `ExplorerSpec` and `AddressServerSpec`. Please let me know if this is what you expected.

Adding another test to check "txLimit" which would mean abstracting and reusing [this](https://github.com/alephium/explorer-backend/blob/cfc90f0d8ce9ff67fd5a59c107075b3cf1840d91/app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala#L68) test. Don't wanna go too overboard but let me know if you'd like this.

2022-11-17 06:54 UTC, tdroxler commented on app/src/test/scala/org/alephium/explorer/ExplorerSpec.scala
> +      val addressesBody    = limitedAddresses.map(address => s""""$address"""").mkString("[", ",", "]")
it's a shame, but I actually discovered yesterday that you can pass 3 args to `mkString` and not only 1 :sweat_smile:

2022-11-17 06:57 UTC, tdroxler commented on app/src/test/scala/org/alephium/explorer/web/AddressServerSpec.scala
> +  def respectMaxNumberOfAddresses(endpoint: String, address: Address) = {
great idea :+1: it's good to add such test for each endpoint having an address limit. I see it as a "regression test", we make sure we don't remove the limit by mistake.

2022-11-17 06:58 UTC, tdroxler approved these changes
LGTM, thx!

2022-11-18 00:02 UTC, merged